# Generated by Django 3.0.5 on 2020-05-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_clip_link'),
        ('account', '0004_auto_20200509_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='love_genres',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='users', to='music.Genre'),
        ),
    ]
