# Generated by Django 3.0.5 on 2020-05-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_track_counts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackuser',
            options={'ordering': ('added',)},
        ),
    ]
