# Generated by Django 3.0.5 on 2020-04-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200424_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='clip_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
