# Generated by Django 3.0.5 on 2020-05-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_clip_link'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='singer',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='singer',
            name='slug',
        ),
    ]
