# Generated by Django 3.0.5 on 2020-05-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20200510_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='singers',
            field=models.ManyToManyField(related_name='songs', to='music.Singer'),
        ),
    ]
